#!/usr/bin/env python

import argparse
import sys
import os
import copy
import math

import rospy
import arm_scenario_simulator as arm_sim

from geometry_msgs.msg import Point, Quaternion
from std_msgs.msg import Empty


def axis_to_quat(axis, angle):
    sin = math.sin(angle/2)
    return Quaternion(w=math.cos(angle/2), x=sin*axis[0], y=sin*axis[1], z=sin*axis[2])

class Environment:

    def add_object(self, obj):
        self.objects[obj.gazebo_name] = obj

    def __init__(self):
        self.objects = {}

        self.add_object( arm_sim.Button('button1').spawn(Point(x=0.5, y=-0.05, z=0.76)) )
        self.add_object( arm_sim.Lever('lever1').spawn(Point(x=0.75, y=0.55, z=0.76) )) #,orientation=axis_to_quat([0,0,1], -math.pi/2 )
        self.add_object( arm_sim.Light('light1',{'r':255,'g':0,'b':0}).spawn('round', Point(x=0.8, y=0.1, z=0.76) ))
        self.add_object( arm_sim.Light('light2',{'r':0,'g':255,'b':0}).spawn('square',Point(x=0.8, y=0.3, z=0.76) ))

        self.add_object( arm_sim.GazeboObject('cube1').spawn(    'DREAM_cube',      Point(x=0.5, y=0.55, z=0.78) ))
        self.add_object( arm_sim.GazeboObject('cylinder1').spawn('DREAM_cylinder',  Point(x=0.6, y=0.2, z=0.78) ))
        self.add_object( arm_sim.GazeboObject('cylinder2').spawn('DREAM_cylinder',  Point(x=1.1, y=0.35, z=0.95) ))

        # the following objects are not spawn, cause already present in the world before this script i run
        self.add_object( arm_sim.Pocket('table/pocket') )
        self.add_object( arm_sim.Light('light_table0',{'r':255,'g':255,'b':255}) )
        self.add_object( arm_sim.Light('light_table1',{'r':255,'g':255,'b':0}) )
        self.add_object( arm_sim.Light('light_table2',{'r':0,'g':255,'b':255}) )

    def delete_models(self):
        for obj in self.objects.keys(): self.objects[obj].__del__()

    def rules(self):
        objects = self.objects

        ''' Light up light1 if the button is pressed '''
        if objects['button1'].is_pressed(): objects['light1'].turn_on()
        else: objects['light1'].turn_off()

        ''' Light up light2 if the lever is pushed '''
        if objects['lever1'].is_pushed(): objects['light2'].turn_on()
        else: objects['light2'].turn_off()

        ''' Light up light_table2 if there is something in the pocket'''
        if objects['table/pocket'].is_active(): objects['light_table2'].turn_on()
        else: objects['light_table2'].turn_off()

        ''' Light up light_table0 if lever is pushed, or if the button is pushed and there is smth in the pocket
        The color depend on what is  'pressed/pushed '''
        condition = objects['lever1'].is_pushed() or ( objects['table/pocket'].is_active() and objects['button1'].is_pressed() )
        r,g,b = 0,255,0
        if objects['button1'].is_pressed() and objects['lever1'].is_pushed(): g,b = 0,255
        objects['light_table0'].set_color(r,g,b)
        objects['light_table0'].set_on(condition)

        ''' Light up light_table1 if lever is pushed and the button is not pushed
        The color depend on what the content of the pocket '''
        condition = objects['lever1'].is_pushed() and not objects['button1'].is_pressed()
        r,g,b = 255,0,0
        if objects['table/pocket'].is_active(): b=255
        objects['light_table1'].set_color(r,g,b)
        objects['light_table1'].set_on(condition)


    def run(self):
        rate = rospy.Rate(100)
        while not rospy.is_shutdown():
            self.rules()
            rate.sleep()


def main():
    rospy.init_node("DREAM_environment_demo")
    env = Environment()
    rospy.on_shutdown(env.delete_models)
    print('sleeping to let sucriber notify master')
    rospy.sleep(1)
    print('Go')
    #rospy.wait_for_message("/robot/sim/started", Empty)
    env.run()


if __name__ == '__main__':
    try: sys.exit(main())
    except rospy.ROSInterruptException,e : pass
